version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
    networks:
      - tunrtc-net

  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - tunrtc-net

  signal-server:
    build:
      context: ../signal-server
      dockerfile: Dockerfile
    networks:
      - tunrtc-net

  coturn:
    image: coturn/coturn
    ports:
      - "3478:3478/udp"
      - "3478:3478/tcp"
    command:
      - "-n"
      - "--log-file=stdout"
      - "--min-port=49152"
      - "--max-port=65535"
    networks:
      - tunrtc-net

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: tunrtc
      POSTGRES_USER: user
      POSTGRES_PASSWORD: "2012704"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d tunrtc" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tunrtc-net

  redis:
    image: redis:latest
    networks:
      - tunrtc-net

  janus:
    build:
      context: ./janus
    ports:
      - "8088:8088"
      - "8188:8188"
      - "10000-10200:10000-10200/udp"
    networks:
      - tunrtc-net

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - tunrtc-net

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - tunrtc-net

networks:
  tunrtc-net:
    driver: bridge

volumes:
  postgres_data:
